---

- name: "Install docker dependencies"
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "apt-transport-https"
    - "ca-certificates"

- name: "Add Docker Repo APT Key"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "{{ docker_apt_key }}"
    state: "present"
  register: "add_repository_key"
  ignore_errors: true

- name: "Add Docker Repository"
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: "present"
    update_cache: True

- name: "Install Docker"
  apt:
    name: "docker-{{ docker_edition }}={{ docker_version }}"
    state: "present"

- name: "Enable Docker systemd service"
  service:
    name: "docker"
    state: "started"
    enabled: "yes"

- name: "Prepare default daemon configuration"
  copy:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"

- name: "Set periodic docker system prune"
  cron:
    name: 'docker-prune'
    minute: "0"
    hour: "*/2"
    job: "docker container prune -f"


- name: "Add users to docker group"
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: 'yes'
  with_items: '{{ docker_group_members }}'
  when: 'docker_group_members is defined'


- name: "Install Docker Compose"
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    force: True
    mode: "0755"
  when: docker_install_docker_compose
